baseURL = "https://sadiqalaboudi.github.io/"
locale = "en"
defaultContentLanguage = "en"
title = "Sadiq Al-Aboudi"

disableKinds = ["taxonomy", "term"]

[languages.en]
label = "English"
direction = "ltr"
weight = 1

[languages.ar]
label = "العربية"
direction = "rtl"
weight = 2

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

# --- Typst Configuration ---
[mediaTypes."text/typst"]
suffixes = ["typ"]
delimiter = "."

[outputFormats.Typst]
mediaType = "text/typst"
baseName = "resume"
isPlainText = true
notAlternative = true

[outputs]
home = ["html", "Typst"]
page = ["html"]